### ISSUE TITLE
Supported wallets for ETH.

### ISSUE THREAD

**Issue by Hannsek** [trezor/definitions#10]
Include wallets below in eth tokens definitions:

[Trezor Suite](https://trezor.io/trezor-suite), [Rabby](https://rabby.io/), [Metamask](https://metamask.io/), [My Crypto](https://mycrypto.com/)

**Comment by matejcik** [comment]
linkspls?

**Comment by grdddj** [comment]
We currently have `"MyEtherWallet": "https://www.myetherwallet.com"` in the list of wallets, should we delete it, or still use it together with those 4 above?

Also, one consideration, `coins_details.json` currently contains around `13_000` tokens, and we are duplicating these 4/5 wallets in each and every entry. It makes the file quite big - `11 MB` right now. Is it OK, or do we want to save space by defining this wallet list on a top-level and then assuming it is valid for all entries starting with `erc20:XXX`?

**Comment by prusnak** [comment]
> Is it OK, or do we want to save space by defining this wallet list on a top-level and then assuming it is valid for all entries starting with `erc20:XXX`?

I think this makes sense.

**Comment by matejcik** [comment]
> Also, one consideration, `coins_details.json` currently contains around `13_000` tokens, and we are duplicating these 4/5 wallets in each and every entry. It makes the file quite big - `11 MB` right now. Is it OK, or do we want to save space by defining this wallet list on a top-level and then assuming it is valid for all entries starting with `erc20:XXX`?

For now, let's not do that. We don't care about the file size that much, the file is consumed by a cron script. The space saving would come at the cost of developer time of trezor.io website, which is very scarce right now.

One thing we can do is set `indent=0`, but we don't want to completely turn off pretty-printing either because from time to time humans will want to look at the diff.

**Comment by matejcik** [comment]
> We currently have `"MyEtherWallet": "https://www.myetherwallet.com"` in the list of wallets, should we delete it, or still use it together with those 4 above?

remove it.

**Comment by grdddj** [comment]
> 



> > Also, one consideration, `coins_details.json` currently contains around `13_000` tokens, and we are duplicating these 4/5 wallets in each and every entry. It makes the file quite big - `11 MB` right now. Is it OK, or do we want to save space by defining this wallet list on a top-level and then assuming it is valid for all entries starting with `erc20:XXX`?
> 
> For now, let's not do that. We don't care about the file size that much, the file is consumed by a cron script. The space saving would come at the cost of developer time of trezor.io website, which is very scarce right now.
> 
> One thing we can do is set `indent=0`, but we don't want to completely turn off pretty-printing either because from time to time humans will want to look at the diff.

Right, reverted the change. Funnily enough, just setting `indent=1` decreased the file size from `11 MB` to `6.5 MB` - there were a lot of spaces before

**Comment by grdddj** [comment]
> > We currently have `"MyEtherWallet": "https://www.myetherwallet.com"` in the list of wallets, should we delete it, or still use it together with those 4 above?
> 
> remove it.

Removed in [d36e835](https://github.com/trezor/definitions/pull/13/commits/d36e8353462704367991bc7d4a5f4abc025531d4)
