### ISSUE TITLE
Include object key as id in coins_details.json

### ISSUE THREAD

**Issue by techi602** [trezor/definitions#14]
For purpose of parsing the `coins_details.json` file from trezor.io it is required that the object key will be part of the object.

So instead of dict
```
"coins": {
"erc20:BTT:BTT": {
   "coingecko_id": "bittorrent",
   "name": "BitTorrent",

```
It would be changed to list with id:
```
"coins": [
{
   "id": "erc20:BTT:BTT",
   "coingecko_id": "bittorrent",
   "name": "BitTorrent",
```
(or keep the dict and just include id in the object)

The main reason is that trezor.io json parser for chunked data can not resolve matching key to the object and this change would be currently easiest one. 

The change should be backwards compatible. (trezor.io can currently parse both formats)

**Comment by prusnak** [comment]
> (or keep the dict and just include id in the object)

I prefer this because this is backwards compatible.

**Comment by matejcik** [comment]
backwards compatible with what? nobody but the tio/coins backend is (supposed to be) consuming this file

**Comment by prusnak** [comment]
Aha, I thought others are using this as well. If that's not the case, feel free to break the compat.

**Comment by grdddj** [comment]
Done in https://github.com/trezor/definitions/pull/15 - I have kept the dict structure, it is more versatile than a list.

The current `coins_details.json` from that PR can be tried at https://raw.githubusercontent.com/trezor/definitions/grdddj/include_object_id/coins_details.json

**Comment by techi602** [comment]
> Done in #15 - I have kept the dict structure, it is more versatile than a list.
> 
> The current `coins_details.json` from that PR can be tried at https://raw.githubusercontent.com/trezor/definitions/grdddj/include_object_id/coins_details.json

It is OK for our needs, thanks!
