### ISSUE TITLE
EVM NFT token definitions

### ISSUE THREAD

**Issue by tomasklim** [trezor/definitions#26]
**Spec:** 

There are definitely not all "legit" NFT collections on CoinGecko but it is a good start.
Missing "legit" collections are e.g. 
https://etherscan.io/token/0xe8b651a8dbca7aa9032e629657936edcc2bb438c from 1Inch
https://etherscan.io/token/0x1645787ddcb380932130f0d8c22e6bf53a38e725 from Rabby

Prerequisite for reverting https://github.com/trezor/trezor-suite/pull/11077
Prerequisite for https://github.com/trezor/trezor-suite/issues/8004

https://api.coingecko.com/api/v3/nfts/list?per_page=100&page=1 (there is around 39 pages of 100 items)

Example of data
```
  {
    "id": "lootprints-for-mooncats",
    "contract_address": "0x1e9385ee28c5c7d33f3472f732fb08ce3cebce1f",
    "name": "lootprints (for MoonCats)",
    "asset_platform_id": "ethereum",
    "symbol": "📜"
  },
  {
    "id": "ethlings",
    "contract_address": "0x8a1abd2e227db543f4228045dd0acf658601fede",
    "name": "Ethlings",
    "asset_platform_id": "polygon-pos",
    "symbol": "😉"
  },
  {
    "id": "pawnshop-gnomies",
    "contract_address": null,
    "name": "Pawnshop Gnomies",
    "asset_platform_id": "solana",
    "symbol": "PAWNSHOPGNOMIE"
  },
```

Solana does not have `contract_address` so let's truncate records without `contract_address`. It is not possible to indentify collection by CoinGecko's `id` with data we have.

The only thing which is important for us is that NFT with specific `contract_address` exists on specific `chainId`. That is all we need to know. As Solana NFTs are out of game and Cardano is not in the list of platforms, let's use the structure from token definitions.
List of platforms with NFTs on CoinGecko https://api.coingecko.com/api/v3/asset_platforms?filter=nft

Structure same as token-definitions
`https://data.trezor.io/firmware/nft-definitions/chain-id/${chainId}/nft-${contractAddress}.dat` we just do `HEAD` request to find out if data are there or not. It does not even need to be `.dat`

**Comment by matejcik** [comment]
We can add this to `definitions-latest.json` but adding it to `data.trezor.io/firmware/definitions` does not make sense at this point / with this spec.

As I was saying on Slack, this tree is not just an arbitrary data store, it's "trustable by firmware" data store. In that context, it's highly unclear what data should there be. If all that is needed is "does this nft exist y/n" then we can add a separate `nfts.json` with this info.

**Comment by matejcik** [comment]
as discussed, we will not be making this part of the definitions repo for now
