### ISSUE TITLE
TS5 supported assets defintion into JSON

### ISSUE THREAD

**Issue by VojtaStr** [trezor/definitions#30]
Hi, for e-shop we need to work in BE/Admin/FE with specs for TS5 device.

Could you please add explicitly which assets are supported by TS5 into the JSON, where all assets are defined?

**Acceptance criteria:**

- the JSON includes TS5 supported assets 
https://raw.githubusercontent.com/trezor/definitions/main/coins_details.json

**Comment by matejcik** [comment]
fixed in #3781
