### ISSUE TITLE
Fix the ticker for TAIKO token

### ISSUE THREAD

**Issue by swarna1101** [trezor/definitions#32]
Hi @tomasklim, 
The ticker for TAIKO token is incorrect on the [website](https://trezor.io/coins), instead of TKO, it will be **TAIKO**. Can you pls fix this. As a proof, I have attached screenshot. Also pls tell the process to add the symbol for a token, we can do it and provide necessary things from our end. Looking forward to get this corrected soon. Thanks.

TAIKO token on taikoscan: https://taikoscan.io/token/0xa9d23408b9ba935c230493c40c73824df71a0975
TAIKO token on etherscan: https://etherscan.io/address/0x10dea67478c5f8c5e2d90e5e9b26dbe60c54d800

![image](https://github.com/user-attachments/assets/37febdd0-9318-462f-b2bb-65f1db6d4931)

**Comment by matejcik** [comment]
fixed in 231a031c902b

> Also pls tell the process to add the symbol for a token, we can do it and provide necessary things from our end. Looking forward to get this corrected soon. Thanks.

no idea, this should be pulled from CoinGecko. this repository is not responsible for the icons :woman_shrugging:

**Comment by swarna1101** [comment]
> fixed in [231a031](https://github.com/trezor/definitions/commit/231a031c902b93a0ebacd48c33742a3b5551f72f)
> 
> > Also pls tell the process to add the symbol for a token, we can do it and provide necessary things from our end. Looking forward to get this corrected soon. Thanks.
> 
> no idea, this should be pulled from CoinGecko. this repository is not responsible for the icons 🤷‍♀️

still able to see the error? 
<img width="1700" alt="image" src="https://github.com/user-attachments/assets/95d67e25-9b2c-488d-b4cb-049e8c662c7b">
